---
version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    working_directory: ~/cfdev
    steps:
      - checkout
      - run: echo "$(sw_vers)"
      - run: echo "$(which hyperkit)"
      - run: echo "$(hyperkit -h)"
