---
version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    working_directory: ~/cfdev
    steps:
      - run: echo "$(top -l 1 -s 0 | grep PhysMem)"
      - checkout
      - run: brew tap cloudfoundry/tap
      - run: brew install cf-cli
      - run: echo "$(sw_vers)"
      - run: echo "$(top -l 1 -s 0 | grep PhysMem)"
      - run: echo y | cf install-plugin testbinary -f
      - run: echo "$(top -l 1 -s 0 | grep PhysMem)"
      - run: cf dev start
