---
version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    working_directory: ~/cfdev
    steps:
      - checkout
      - run: brew tap cloudfoundry/tap
      - run: brew install cf-cli
      - run: echo "$(sw_vers)"
      - run: cf install-plugin testbinary
      - run: cf dev start
