---
version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    working_directory: ~/cfdev
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: echo 'export GOPATH=$HOME/cfdev' >> $BASH_ENV
      - run: echo 'sw_vers'
