---
version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    working_directory: ~/cfdev
    environment:
      - CFDEV_HOME: "~/.cfdev"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: brew tap cloudfoundry/tap
      - run: brew install cf-cli
      - run: echo "$(sw_vers)"
      - run: echo "$(top -l 1 -s 0 | grep PhysMem)"
      - run: cf install-plugin testbinary -f
      - run: echo "$(top -l 1 -s 0 | grep PhysMem)"
      - run: cf dev start
