image: dhcpcd
org: pivotal
disable-content-trust: true
config:
  binds:
    - /run/resolvconf:/etc
  capabilities:
    - CAP_NET_ADMIN
    - CAP_NET_BIND_SERVICE
    - CAP_NET_RAW
    - CAP_SYS_ADMIN
