onboot:
  - name: add-garden-ip-to-loopback
    image: alpine:3.6
    capabilities:
      - all
    net: host
    command: ["sh", "-c", "ifconfig lo:1 add 10.0.0.10 netmask 255.255.255.254 up"]

  - name: ensure-vcap-folder-exists
    image: alpine:3.6
    capabilities:
      - CAP_SYS_ADMIN
    binds:
      - /var/:/host_var:rbind,rshared
    rootfsPropagation: shared
    command: ["sh", "-c", "mkdir -p /host_var/lib/vcap && \
                           mount -v --bind /host_var/lib/vcap /host_var/lib/vcap && \
                           mount -v --make-shared /host_var/lib/vcap && \
                           ln -vs /var/lib/vcap /host_var/vcap"]

  - name: mount-deps
    image: linuxkit/mount:41685ecc8039643948e5dff46e17584753469a7a
    command: ["/usr/bin/mountie", "-device", "/dev/sda2", "/var/vcap/cache"]

services:
  - name: garden
    image: pivotal/garden-runc:dev
    rootfsPropagation: shared
    binds:
      - /var/lib:/var/lib
      - /var/vcap:/var/vcap:rshared,rbind
      - /etc/resolv.conf:/etc/resolv.conf

  - name: setup-bosh-lite-routing
    image: pivotal/bosh-lite-routing:dev
    net: host
    capabilities: ["all"]
    binds:
      - /var/lib/vcap:/var/vcap

  - name: expose-garden-port
    image: alpine:3.6
    net: none
    binds:
      - /usr/bin/vpnkit-expose-port:/usr/bin/vpnkit-expose-port
      - /var/vpnkit:/port
    command: ["/usr/bin/vpnkit-expose-port","-i", "-no-local-ip",
              "-host-ip","127.0.0.1",
              "-host-port","8888",
              "-container-ip","127.0.0.1",
              "-container-port","7777"]

  - name: expose-bosh-http-port
    image: alpine:3.6
    net: none
    binds:
      - /usr/bin/vpnkit-expose-port:/usr/bin/vpnkit-expose-port
      - /var/vpnkit:/port
    command: ["/usr/bin/vpnkit-expose-port","-i", "-no-local-ip",
              "-host-ip","10.245.0.2",
              "-host-port","25555",
              "-container-ip","10.245.0.2",
              "-container-port","25555"]

  - name: expose-bosh-uaa
    image: alpine:3.6
    net: none
    binds:
      - /usr/bin/vpnkit-expose-port:/usr/bin/vpnkit-expose-port
      - /var/vpnkit:/port
    command: ["/usr/bin/vpnkit-expose-port","-i", "-no-local-ip",
              "-host-ip","10.245.0.2",
              "-host-port","8443",
              "-container-ip","10.245.0.2",
              "-container-port","8443"]

  - name: expose-bosh-credhub
    image: alpine:3.6
    net: none
    binds:
      - /usr/bin/vpnkit-expose-port:/usr/bin/vpnkit-expose-port
      - /var/vpnkit:/port
    command: ["/usr/bin/vpnkit-expose-port","-i", "-no-local-ip",
              "-host-ip","10.245.0.2",
              "-host-port","8844",
              "-container-ip","10.245.0.2",
              "-container-port","8844"]

  - name: expose-bosh-ssh-port
    image: alpine:3.6
    net: none
    binds:
      - /usr/bin/vpnkit-expose-port:/usr/bin/vpnkit-expose-port
      - /var/vpnkit:/port
    command: ["/usr/bin/vpnkit-expose-port","-i", "-no-local-ip",
              "-host-ip","10.245.0.2",
              "-host-port","22",
              "-container-ip","10.245.0.2",
              "-container-port","22"]

  - name: expose-router-http-port
    image: alpine:3.6
    net: none
    binds:
      - /usr/bin/vpnkit-expose-port:/usr/bin/vpnkit-expose-port
      - /var/vpnkit:/port
    command: ["/usr/bin/vpnkit-expose-port","-i", "-no-local-ip",
              "-host-ip","10.144.0.34",
              "-host-port","80",
              "-container-ip","10.144.0.34",
              "-container-port","80"]

  - name: expose-router-https-port
    image: alpine:3.6
    net: none
    binds:
      - /usr/bin/vpnkit-expose-port:/usr/bin/vpnkit-expose-port
      - /var/vpnkit:/port
    command: ["/usr/bin/vpnkit-expose-port","-i", "-no-local-ip",
              "-host-ip","10.144.0.34",
              "-host-port","443",
              "-container-ip","10.144.0.34",
              "-container-port","443"]

  - name: expose-router-ssh-port
    image: alpine:3.6
    net: none
    binds:
      - /usr/bin/vpnkit-expose-port:/usr/bin/vpnkit-expose-port
      - /var/vpnkit:/port
    command: ["/usr/bin/vpnkit-expose-port","-i", "-no-local-ip",
              "-host-ip","10.144.0.34",
              "-host-port","2222",
              "-container-ip","10.144.0.34",
              "-container-port","2222"]

  - name: expose-router-tcp-ports
    image: alpine:3.6
    net: none
    binds:
      - /usr/bin/expose-multiple-ports:/usr/bin/expose-multiple-ports
      - /var/vpnkit:/port
    command: ["/usr/bin/expose-multiple-ports",
              "-container-ip","10.144.0.34",
              "-start-port","1024",
              "-end-port","1123"]
